#!/usr/bin/python3

import socket
#from termcolor import colored

sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
socket.setdefaulttimeout(2)

host = input("[*] Enter The Host to Scan: ") 
#port = int(raw_input("[*] Enter The Port to Scan: "))

def portscanner(port):
        if sock.connect_ex((host,port)):
                print("[!!] Port %d is closed" % (port)) 
        else:
                print("[+] Port %d is open" % (port)) 

#portscanner(port)

for port in range(1,1000):
	portscanner(port) 

 
